zookeeper:
  image: jplock/zookeeper:3.4.6
  volumes:
    - "/tmp/zookeeper:/tmp/zookeeper"
  ports:
    - "2181:2181"

master:
  image: fpgeek/mesos:v0.22.1
  command: mesos-master
  ports:
    - "5050:5050"
  links:
   - "zookeeper:zookeeper"
  environment:
    MESOS_CLUSTER: marathon
    MESOS_HOSTNAME: 10.42.15.11
    MESOS_LOG_DIR: /var/log/mesos
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_QUORUM: 1
    MESOS_ZK: zk://zookeeper:2181/mesos

slave1:
  image: fpgeek/mesos:v0.22.1
  command: supervisord -n
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  links:
    - "zookeeper:zookeeper"
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: 10.42.15.11
    MESOS_LOG_DIR: /var/log/mesos
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_MASTER: zk://zookeeper:2181/mesos

slave2:
  image: fpgeek/mesos:v0.22.1
  command: supervisord -n
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  links:
    - "zookeeper:zookeeper"
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: 10.42.15.11
    MESOS_LOG_DIR: /var/log/mesos
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_MASTER: zk://zookeeper:2181/mesos

slave3:
  image: fpgeek/mesos:v0.22.1
  command: supervisord -n
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  links:
    - "zookeeper:zookeeper"
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: 10.42.15.11
    MESOS_LOG_DIR: /var/log/mesos
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_MASTER: zk://zookeeper:2181/mesos

marathon:
  image: mesosphere/marathon:v0.8.1
  ports:
    - "8080:8080"
  volumes:
    - "/tmp:/tmp"
    - "/var/log:/var/log"
  links:
    - "zookeeper:zookeeper"
    - "master:master"
  command: "--master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon --checkpoint --event_subscriber http_callback"

chronos:
  image: mesosphere/chronos:chronos-2.3.4-1.0.81.ubuntu1404-mesos-0.22.1-1.0.ubuntu1404
  ports:
    - "4400:8080"
  links:
    - "zookeeper:zookeeper"
    - "master:master"
  command: "/usr/bin/chronos --master zk://zookeeper:2181/mesos --zk_hosts zk://zookeeper:2181/mesos"